### ISSUE TITLE
Broken Link in Articles

### ISSUE THREAD

**Issue by ityreh** [VidyasagarMSC/Awesome-AI#1]
The following Link seems to be broken.
**broken link**: https://www.ibm.com/developerworks/library/cc-beginner-guide-machine-learning-ai-cognitive/index.html
**solution**: https://developer.ibm.com/articles/cc-beginner-guide-machine-learning-ai-cognitive/

**Comment by VidyasagarMSC** [comment]
Fixed. Thanks
